name: Push Jobs
on:
  push:
    branches:
      - main
  repository_dispatch:
jobs:
  test:
    name: Test Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install
      - name: Run ESLint
        run: pnpm lint
      - name: Build Packages
        run: pnpm build
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: "packages/server"
          preCommands: wrangler d1 migrations apply api-bachman-dev --remote
